alias flap='tmux attach -t flap'
alias flap-init='tmuxinator flap'
alias flap-help='flap-help.sh'
alias flap-bheap='flap-basic.sh ~/Processes/FLAP/BHEAP/todo.txt 5'
alias flap-appcave='flap-basic.sh ~/Processes/FLAP/APPCAVE/todo.txt 5'
alias flap-readme='flap-basic.sh ~/Processes/FLAP/readme.txt 60'
alias flap-agenda='flap-basic.sh ~/Processes/FLAP/agenda.txt 10'
